version: '3'

services:
  pivio:
    build: .
    ports:
     - "9123:9123"

  elasticsearch:
    image: elasticsearch:6.4.3
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
